[package]
name = "vm-allocator"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
libc = "*"

[dependencies.vm-memory]
git = "https://github.com/sboeuf/vm-memory"
branch = "add_fd_support"
features = ["backend-mmap"]

