[package]
name = "vub"
version = "0.1.0"
authors = ["Sergio Lopez <slp@redhat.com>"]
description = "Rust implementation of the vhost-user-blk personality"
edition = "2018"
license = "Apache-2.0"

[dependencies]
bitflags = ">=1.0.1"
env_logger = "0.5.12"
epoll = ">=4.0.1"
io-uring = "0.2"
libc = ">=0.2.39"
log = "0.4.6"
nix = ">=0.12"
